### ISSUE TITLE
Not working in VSCode

### ISSUE THREAD

**Issue by NayamAmarshe** [SanderRonde/prettier-plugin-sort-imports#1]
I'm unable to make this plugin work. I first did:
`yarn add prettier-plugin-sort-imports`
but it doesn't seem to sort imports.
I'm using Prettier VSCode extension and npm package.

**Comment by NayamAmarshe** [comment]
It works now. For some reason it's not automatically loaded by prettier.

I had to create a `.prettierrc` with
```json
{
  "sortingMethod": "lineLength",
  "pluginSearchDirs": ["./node_modules"],
  "plugins": ["./node_modules/prettier-plugin-sort-imports"]
}
```

**Comment by SanderRonde** [comment]
I'm pretty sure the prettier vscode extension does not reload its plugins until you restart the extension (or vscode, or maybe change the rc file). I think that's the reason for it not working.

Regardless I think that's probably an issue with the prettier vscode extension or prettier itself so I'll close this issue.
