### ISSUE TITLE
Fails to resolve .prettierrc.mjs

### ISSUE THREAD

**Issue by mithodin** [SanderRonde/prettier-plugin-sort-imports#11]
When running in a project which uses .prettierrc.mjs, prettier-plugin-sort-imports fails to resolve its location, since it is not listed in the list of possible config filenames in https://github.com/SanderRonde/prettier-plugin-sort-imports/blob/master/app/src/sorters/import-type.ts. However, prettier 3 supports this filename.

If viable, I would suggest using prettier's built-in resolveConfigFile() instead of duplicating the implementation here.

**Comment by SanderRonde** [comment]
Thanks for the report. I'll add it
