### ISSUE TITLE
Doesn't remove New Lines when `newlineBetweenTypes` is false

### ISSUE THREAD

**Issue by shalev-evinced** [SanderRonde/prettier-plugin-sort-imports#5]
Hello,
If there're new lines between imports, they aren't removed, even if the `newlineBetweenTypes` type is explicitly `false`.

Example:
Source Code:
```ts
import { SpanKind } from '@opentelemetry/api'
import { SpanExporter } from '@opentelemetry/sdk-trace-base'

import logger from './common/logger'
```

The expected result, which doesn't happen:
```ts
import { SpanKind } from '@opentelemetry/api'
import { SpanExporter } from '@opentelemetry/sdk-trace-base'
import logger from './common/logger'
```

Thank you!

**Comment by SanderRonde** [comment]
Can you post your `.prettierrc`? It could be related to the `importTypeOrder` option not being used (or maybe it is and it's a bug)

**Comment by SanderRonde** [comment]
I'll be closing this issue since there hasn't been a response in quite a while
