### ISSUE TITLE
Do not work for transitive dependencies

### ISSUE THREAD

**Issue by mestihudson** [SanderRonde/prettier-plugin-sort-imports#6]
I faced the following situation:
I had a file like this 
```typescript
import { Injectable, NestMiddleware } from '@nestjs/common';
import { NextFunction, Request, Response } from 'express';
import { v4 as uuidv4 } from 'uuid';

@Injectable()
...
```
That was modified by `prettier-plugin-sort-imports` to
```typescript
import { Injectable, NestMiddleware } from '@nestjs/common';
import { v4 as uuidv4 } from 'uuid';

import { NextFunction, Request, Response } from 'express';

@Injectable()
...
```
Because `express` package is a transitive dependency from one of my declared dependencies.

I'm search a way to resolve this problem, using `npm-view` lib, but at version 8.0.0, it was deprecated.
Now I think to use `npm-view` cli executable, but I am not sure that is a good solution.
If you have some idea, let me know.

**Comment by SanderRonde** [comment]
Regarding the plugin: I think when you get to the point where you import a transitive dependency directly, it's not really a transitive dependency anymore and becomes a direct (dev) dependency and you should probably just add it to your package.json.

Not really sure what the problem you're having here is though. Is it that the plugin won't detect that it's a transitive dependency? Or is it that you just want to list all transitive dependencies? 

I'll close this now as a wontfix so it doesn't show up as an open issue anymore, but of course you're welcome to keep asking questions :)

**Comment by mestihudson** [comment]
I got your point, and I guess you right.
If you import a component, it becomes a direct dependency, no more should be a transtitive, because you have to explicit your dependencies.
Thanks by your thought.
Congratulations by your work.

**Comment by SanderRonde** [comment]
Yep exactly, it also ensures that your application doesn't suddenly break if it's no longer a transitive dependency through the other package and is no longer installed.
